{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "echoserver.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "echoserver.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Exact" }}
            backend:
              service:
                name: {{ include "echoserver.fullname" $ }}
                port:
                  number: {{ .servicePort | default $.Values.service.port }}
          {{- end }}
{{- end }}