# Default values for echoserver.

nameOverride: ""
fullnameOverride: ""
replicaCount: 1
imagePullSecrets: []
image:
  repository: 395364994606.dkr.ecr.eu-west-1.amazonaws.com/echoserver
  pullPolicy: IfNotPresent
  tag: "sha-ee4c04b"
podSecurityContext: {}
# Example:
# fsGroup: 2000

securityContext: {}
# Example:
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources: {}
# Example:
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector:
  role: application
  
tolerations: []
affinity: {}
topologySpreadConstraints: []
# Example:
# - maxSkew: 1
#   topologyKey: topology.kubernetes.io/zone
#   whenUnsatisfiable: DoNotSchedule
#   labelSelector:
#     matchLabels:
#       app.kubernetes.io/name=hub

volumes: []
volumeMounts: []
env: []
# Example:
# - name: MY_ENV_VAR
#   value: my_value

podAnnotations: {}
podLabels: {}
service:
  type: NodePort
  port: 80
  targetPort: 8080
  annotations: {}
  labels: {}
serviceAccount:
  name: ""
serviceMonitor:
  enabled: false
  additionalMetricsRelabels: {}
  additionalRelabeling: []
  labels: {}
  path: /metrics
  interval: 30s
  scrapeTimeout: 30s
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-00e7e732c9b48a84f,subnet-00efaa0cda7a100e2
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Exact
  tls: []
