name: GitOps Repository Update

on:
  workflow_run:
    workflows: ["Continuous Delivery - Docker Image"]
    types:
      - completed
    branches:
      - main

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy (default: sha-<short commit SHA>)'
        required: false

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  VALUES_FILE_PATH: charts/echoserver/values.yaml

jobs:
  update-gitops:
    name: Update GitOps Repository
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: determine-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.image_tag }}" ]]; then
            echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
            echo "IMAGE_TAG=sha-$SHORT_SHA" >> $GITHUB_OUTPUT
          fi

      - name: Install yq
        uses: mikefarah/yq@master

      - name: Update image version in values.yaml
        run: |
          echo "Updating image tag to ${{ steps.determine-tag.outputs.IMAGE_TAG }}"

          yq -i '.image.tag = "${{ steps.determine-tag.outputs.IMAGE_TAG }}"' ${{ env.VALUES_FILE_PATH }}
          yq -i '.image.repository = "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}"' ${{ env.VALUES_FILE_PATH }}

          echo "Updated values.yaml:"
          cat ${{ env.VALUES_FILE_PATH }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.VALUES_FILE_PATH }}
          git commit -m "Update image to ${{ steps.determine-tag.outputs.IMAGE_TAG }}"
          git push origin HEAD:${{ github.ref }}

          echo "Successfully updated values.yaml with new image tag: ${{ steps.determine-tag.outputs.IMAGE_TAG }}"